// Generated by CoffeeScript 1.6.3
var TinyTotalizer, assert, vows,
  _this = this;

vows = require('vows');

assert = require('assert');

TinyTotalizer = require('../lib/tiny-totalizer');

vows.describe('return key (false) test').addBatch({
  'コンストラクタ: calcReturnIsKey: false': {
    topic: function() {
      var tt;
      tt = new TinyTotalizer({
        fuzzyLevel: 1,
        calcReturnIsKey: false
      });
      tt.add('aaa');
      return tt.add('AAA');
    },
    'addの戻り値はセットしたキーのカウント数': function(topic) {
      return assert.equal(topic, 2);
    }
  }
})["export"](module);
